### ISSUE TITLE
ForestHealthTab edits for Jewel

### ISSUE THREAD

**Issue by whmacken** [bcgov/byBEC_shiny#4]
- [x] Add new assignment category: "Not Assigned"
- [x] Change Legend and colour scheme to include Nil and Not assigned. Remove out of range.
- [x] Test upload CSV function
- [x] Add the OHR tickbox function here as well.
- [x] Download .CSV function. a) the pest download should default to the currently selected one, b) the name of the download file should be PESTCODE_ForestHealthDownload, c) the pick list need to be ordered alphabetically. 
- [x] Specific issue with ICHdw3. For example, shows Fd in ICHdw3 and shows Fd plus pests in BGC pest table. But ICHdw3 does not appear in the list view for the Tree x Pest table nor does ICHdw3 get exported to a CSV on download. 
- [x] Add new assignment categories to dropdown picklists. 
- [x] The Nil dark green does not standout enough. Low and Nil can both be green just have to find two that differentiate between each other and standout

**Comment by kdaust** [comment]
@whmacken please pick some colours for me. I dislike choosing colours. https://htmlcolorcodes.com/color-picker/

**Comment by whmacken** [comment]
B8FF33 try this light green
